
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: saas
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - saas_db:/var/lib/postgresql/data

volumes:
  saas_db:
